services:
  app:
    build: .
    container_name: jobcraftai
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - app_data:/app/uploads
    env_file:
      - .env
    restart: unless-stopped

volumes:
  app_data:
